import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { Providers } from "@/components/providers";
import NavBar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative dark`}>
        <header className="fixed top-0 bg-accent text-accent-foreground w-full flex justify-between items-center px-6 py-2 h-16">
          <NavBar />
        </header>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
